name: Run Sync Script

on:
  push:
    branches:
      - main

jobs:
  run_sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"

      - name: Set up Python
        run: uv python install

      - name: Run sync script
        env:
          AT_LOGIN: ${{ secrets.AT_LOGIN }}
          AT_PASSWORD: ${{ secrets.AT_PASSWORD }}
          STARTER_PACK_URI: ${{ secrets.STARTER_PACK_URI }}
        run: uv run sync.py
